# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-03-18 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
