# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-03-24 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('resource_effect', models.CharField(choices=[('increment', 'Increment'), ('decrement', 'Decrement'), ('none', 'None')], max_length=16, verbose_name='resource effect')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AgentRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
            ],
            options={
                'ordering': ('subject',),
            },
        ),
        migrations.CreateModel(
            name='AgentRelationshipRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('inverse_name', models.CharField(max_length=255, verbose_name='name')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('date_and_time', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vocab.Action', verbose_name='action')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('-date_and_time',),
            },
        ),
        migrations.CreateModel(
            name='EconomicResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('planned_start', models.DateTimeField(blank=True, null=True, verbose_name='planned start')),
                ('planned_duration', models.DurationField(blank=True, null=True, verbose_name='planned duration')),
                ('is_finished', models.BooleanField(default=False, verbose_name='is finished')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processes_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuantityKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='QuantityValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_value', models.DecimalField(decimal_places=4, max_digits=11, verbose_name='quantity')),
            ],
            options={
                'ordering': ('unit',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('changed_date', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('quantity_kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='vocab.QuantityKind', verbose_name='quantity kind')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_subclass',
            field=models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], default='person', max_length=16, verbose_name='subclass'),
        ),
        migrations.AddField(
            model_name='agent',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents_changed', to=settings.AUTH_USER_MODEL, verbose_name='changed by'),
        ),
        migrations.AddField(
            model_name='agent',
            name='changed_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='agent',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quantityvalue',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_values', to='vocab.Unit', verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='economicevent',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='vocab.Process', verbose_name='process'),
        ),
        migrations.AddField(
            model_name='economicevent',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_events', to='vocab.Agent', verbose_name='provider'),
        ),
        migrations.AddField(
            model_name='economicevent',
            name='quantity_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vocab.QuantityValue', verbose_name='quantity value'),
        ),
        migrations.AddField(
            model_name='economicevent',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_events', to='vocab.Agent', verbose_name='receiver'),
        ),
        migrations.AddField(
            model_name='economicevent',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vocab.EconomicResource', verbose_name='resource'),
        ),
        migrations.AddField(
            model_name='agentrelationship',
            name='context',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='context_relationships', to='vocab.Agent', verbose_name='context'),
        ),
        migrations.AddField(
            model_name='agentrelationship',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships_created', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='agentrelationship',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships', to='vocab.Agent', verbose_name='object'),
        ),
        migrations.AddField(
            model_name='agentrelationship',
            name='relationship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='vocab.AgentRelationshipRole', verbose_name='relationship'),
        ),
        migrations.AddField(
            model_name='agentrelationship',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relationships', to='vocab.Agent', verbose_name='subject'),
        ),
    ]
