# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_auto_20170324_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ('label',)},
        ),
        migrations.AlterModelOptions(
            name='agentrelationshiprole',
            options={'ordering': ('label',)},
        ),
        migrations.RenameField(
            model_name='action',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='agentrelationshiprole',
            old_name='inverse_name',
            new_name='inverse_label',
        ),
        migrations.RenameField(
            model_name='agentrelationshiprole',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_subclass',
            field=models.CharField(choices=[('Person', 'Person'), ('Organization', 'Organization')], default='Person', max_length=16, verbose_name='subclass'),
        ),
    ]
