# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_auto_20170330_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='agentrelationshiprole',
            name='inverse_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='inverse label'),
        ),
        migrations.AlterField(
            model_name='agentrelationshiprole',
            name='label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='label'),
        ),
    ]
